---
env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
plugins:
  - '@typescript-eslint'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  parser: '@typescript-eslint/parser'
rules:
  import/prefer-default-export: 'off'
  arrow-body-style: 'off'
  import/no-unresolved: 'off'
  import/extensions: 'off'
  max-classes-per-file: 'off'
  no-underscore-dangle: 'off'
